### PR TITLE
Add Ecto changeset support

### LINKED ISSUE #6: Transitions changes the status in-memory, which will fail Ecto's dirty changeset tracking
Apologies for the slight oversight, but I found a "bug" where Gearbox's `transition/3` (and the bang variant) will change the status in memory (returning a new copy, with updated `status`).

While this is great for normal, pure Elixir usage, this will actually make working with Ecto a bit difficult.

For example:

Let's say I have an item, called `Issue`, and I want to transition the state from `unread` to read`.

```elixir
  def update_issue_status(%Issue{} = issue, status) do
    issue
    |> Gearbox.transition!(IssueMachine, status)
    |> Issue.status_changeset(%{status: status})
    |> Repo.update()
  end
```

This would fail, because `Gearbox.transition/3` will change the issue's status in memory, and when it's passed to changeset (and being casted), it'll be ignored, because there are no "changes". To illustrate the step by step flow of status:

```elixir
  def update_issue_status(%Issue{} = issue, status) do
    issue # status is now `unread`
    |> Gearbox.transition!(IssueMachine, status) # status is now `read`
    |> Issue.status_changeset(%{status: status}) # Because `status` is updated to `read`, we are now telling Ecto to change from `status: 'read'` to `status: 'read'`, which will generate a changeset with no changes.
    |> Repo.update() # This will continue executing because changeset without changes is technically valid.
 
  end
```

I'm still thinking about how to deal with this, discussions are very welcomed. One possible way is to have a `validate_transition` API that just does validation without changing the structure in place, but that feels a little weird as well, because this may change the usage/mission of Gearbox (previously was intended to use it everywhere but your schema, but with the change above, it will now require users to use Gearbox at the schema levels. I'm not sure if this is the correct direction to take.

## Temporary Fix:

You can temporarily circumvent this bug by making sure when you feed a structure into `changeset`, you feed the old version of it, so the Changeset will be able to generate a changeset.

### PR DESCRIPTION
**Pull request by edisonywh**
Creating a PR so it's easier to review it here

Closes #6

### CODE REVIEW

**Comment by edisonywh** [comment]
Thanks for the PR @mauricew, I appreciate it :) (feel free to re-open the PR if you want)

Here's some comments that I have that I think would be good to discuss.

1) If we are adding Ecto support, I think it's better to namespace it under a new file, `gearbox/ecto.ex`.

2) As you've shown in your PR, most of the code (namely the condition checks in the `with` pipeline`) are identical to the vanilla Gearbox, so it would be good to refactor them into a single place. The main thing that changes is the `do` block and the error handling part, which leads to the next point:

3) If we were to integrate with Ecto, it might be a better idea to be a proper citizen and use Ecto's `validation_*` and populate the error. We should also add a test to cover the error case.

What I'm sort of envisioning now is something like this below (just an idea, open to discussion):

```
case do_transition(machine, struct, field, block) do
  {:ok, changeset_or_struct} = result -> result
  {:error, changeset_or_struct, reason} = result -> result
end
```

The idea is that you run the validation code inside `do_transition/4`, and the `block` would replace whatever was in the `do` block, so likely a function like `Map.put/3`, or `Ecto.Changeset.change/2`, or even just passing in an atom that indicates if it's vanilla gearbox or Ecto gearbox.

This way it also opens up the error handling for Gearbox.Ecto to maybe do something like add error to the changeset instead of returning Gearbox specific error.

What do you think?

**Comment by mauricew** [comment]
> 1. If we are adding Ecto support, I think it's better to namespace it under a new file, `gearbox/ecto.ex`.

I agree with this, along with aliasing the functions in the base module.

> 2. As you've shown in your PR, most of the code (namely the condition checks in the `with` pipeline`) are identical to the vanilla Gearbox, so it would be good to refactor them into a single place. The main thing that changes is the `do` block and the error handling part

I initially had it use the same code for `transition/3` and `transition_changeset/3` until I realized that returning an ok/error Tuple wouldn't be enough and I'd have to re-extract some of the variables to get it working again.

> 3. If we were to integrate with Ecto, it might be a better idea to be a proper citizen and use Ecto's `validation_*` and populate the error. We should also add a test to cover the error case.

I'm a fan of this since it's more idiomatic to how Ecto would work.  
As for the case where having an API open to post-transition actions (which is a better implementation of what you formerly had as callbacks), it's all dependent on what you want the library to be focused on. If it's being kept strictly to transitioning via struct change or Ecto changeset, then the block functionality can be private. If the direction is more open to  what you're proposing, then the proposal would work.

In any case there seems to be a more work to be done but I'd be willing to look into it in the next few days.

**Comment by edisonywh** [comment]
> As for the case where having an API open to post-transition actions

I am not quite sure what you meant by this, can you elaborate?

If they end up being in different files then they can't be `defp` by definition, but we should still document them to be internal private functions imo.

**Comment by mauricew** [comment]
Ok, I see it a bit more clearly now. I meant to refer to the transition action action itself rather than post-transition, and I also wouldn't be opposed to having the do_transition (or whatever it becomes) method be a documentable way to provide your own action.

**Comment by edisonywh** [comment]
No maybe I'm not expressing myself clearly, I meant to say that I think `do_transition` (the shareable code block between `transition` and `transition_changeset`) should be private and internal - we can't make it private with `defp` because we need to share it with two separate files, but they are not supposed to be used by end users directly.

**Comment by mauricew** [comment]
Ok, understood. I'll have the changes up in a little while.

**Comment by mauricew** [comment]
Just to explain the change here, I created the method`validate_translation` rather than `do_translation`, with the reasoning being I didn't want to tie the action to a block because that seemed to introduce some limitations with passing in the field name. It will return the same error as before which can be passed through, and also an `{:ok, nil}` to specify it's free to go ahead and make the transition.

**Comment by edisonywh** [comment]
@mauricew Sorry for the late reply, I didn't realise you force-pushed a PR 7 days ago, only found out when you commented two days ago!

I took a look and I really like the changes, thanks for the comprehensive test coverage too.

Few comments before I merge it:
- For testing Ecto Changesets, you can also check for `.valid?` to make sure it's invalid, just to make it a little clearer
- Some small nitpicks about formatting, running `mix format` should be fine
- Some docs on README would be great, but I could also add them
- The tests are failing on Travis, there are two errors:
1) Looks like Ecto requires us to bump our minimum Elixir version to 1.8
2) Ecto seems to be complaining about expanding macro in Elixir 1.9?

**Comment by mauricew** [comment]
Got the updates made. Take a look over at the documentation to check if I made a good pattern choice there.
Apparently OTP 23.1 isn't available on Travis so I'm putting it on 23.0.

**Comment by edisonywh** [comment]
🚀🚀🚀 Looks great, thanks for the contribution @mauricew!

I'm gonna go ahead and merge it and release it!

It also just occurred to me that it maybe it would be nice to have a bang variant of the function (so it can be used in a pipeline if you don't expect the states to be invalid). Not sure if that adds a lot of value so I'll raise this in a separate issue

**Pull request merged**
